version: "3"
services:
  master_db:
    container_name: master_db
    image: mvertes/alpine-mongo
    environment:
      - TEAM_NAME=CC_0195_0309

  slave_db:
    container_name: slave_db
    image: mvertes/alpine-mongo
    environment:
      - TEAM_NAME=CC_0195_0309