version: "3"
services:
  rides:
    container_name: rides
    restart: always
    image: rides:latest
    ports:
      - 80:5050
    env:
      - TEAM_NAME=CC_0195_0309
    depends_on:
      - rides_db
  rides_db:
    container_name: rides_db
    image: mongo
    env:
      - TEAM_NAME=CC_0195_0309
